// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0nhZQIrb6eMmLrDd63YXUEc2hIqJ8VIU',
    appId: '1:622666613815:web:d22e40d02f5fbfff5b2bb2',
    messagingSenderId: '622666613815',
    projectId: 'chefito-74733',
    authDomain: 'chefito-74733.firebaseapp.com',
    storageBucket: 'chefito-74733.firebasestorage.app',
    measurementId: 'G-1MDT8BV9DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARzX_kSCdlyiLvvOjeu_C8PY-g63eTHrc',
    appId: '1:622666613815:android:a0198e30cb18f5865b2bb2',
    messagingSenderId: '622666613815',
    projectId: 'chefito-74733',
    storageBucket: 'chefito-74733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Rq8TdAiHZGPoOVkphzPhvDwtkmwEmVw',
    appId: '1:622666613815:ios:37a0f091881af3495b2bb2',
    messagingSenderId: '622666613815',
    projectId: 'chefito-74733',
    storageBucket: 'chefito-74733.firebasestorage.app',
    iosBundleId: 'com.example.chefito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Rq8TdAiHZGPoOVkphzPhvDwtkmwEmVw',
    appId: '1:622666613815:ios:37a0f091881af3495b2bb2',
    messagingSenderId: '622666613815',
    projectId: 'chefito-74733',
    storageBucket: 'chefito-74733.firebasestorage.app',
    iosBundleId: 'com.example.chefito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0nhZQIrb6eMmLrDd63YXUEc2hIqJ8VIU',
    appId: '1:622666613815:web:8c2acfaab273d9cb5b2bb2',
    messagingSenderId: '622666613815',
    projectId: 'chefito-74733',
    authDomain: 'chefito-74733.firebaseapp.com',
    storageBucket: 'chefito-74733.firebasestorage.app',
    measurementId: 'G-7Z8S2L5PCW',
  );
}
